import React, { useState } from 'react';
import { Sparkles, Calendar } from 'lucide-react';
import { Goal, Task, SubTask } from '../types';

interface GoalPlannerProps {
  onAddBreakdown: (task: Omit<Task, 'id' | 'status'>, goal?: Omit<Goal, 'id' | 'progress'>) => void;
  isLoading: boolean;
  setIsLoading: (loading: boolean) => void;
}

export default function GoalPlanner({ onAddBreakdown, isLoading, setIsLoading }: GoalPlannerProps) {
  const [title, setTitle] = useState('');
  const [deadline, setDeadline] = useState('');
  const [error, setError] = useState('');

  const handleAiBreakdown = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) {
      setError('Please enter a goal or task to break down.');
      return;
    }
    setError('');
    setIsLoading(true);

    try {
      const response = await fetch('/api/breakdown', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, description: '', deadline }),
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error || 'Failed to generate task breakdown.');
      }

      const data = await response.json();

      const formattedSubTasks: SubTask[] = (data.subTasks || []).map((st: any, idx: number) => ({
        id: `st-${Date.now()}-${idx}`,
        title: st.title,
        completed: false,
        estimatedDuration: st.estimatedDuration || 25,
      }));

      onAddBreakdown(
        {
          title: data.title || title,
          description: data.description || 'Generated by Sia AI',
          priority: data.priority || 'medium',
          estimatedDuration: data.estimatedDuration || 60,
          category: data.suggestedCategory || 'General',
          subTasks: formattedSubTasks,
          deadline: deadline || undefined,
        },
        deadline ? {
          title: data.title || title,
          description: data.description || 'Custom Sprint',
          deadline: deadline,
        } : undefined
      );

      setTitle('');
      setDeadline('');
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Connecting to Sia failed.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div id="goal-planner-card" className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-5 shadow-sm transition-colors duration-200">
      <div className="mb-3.5 flex items-center justify-between">
        <div>
          <h2 className="text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-widest font-mono flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" /> AI Goal Strategist
          </h2>
          <p className="text-[10px] text-zinc-500">Sia AI will break any goal down into structured sub-sprints.</p>
        </div>
      </div>

      <form onSubmit={handleAiBreakdown} className="space-y-3">
        {/* Main Goal Input */}
        <div>
          <input
            id="goal-title"
            type="text"
            required
            placeholder="Type a big milestone (e.g. Prepare for chemistry midterm)"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            disabled={isLoading}
            className="w-full px-3 py-2 text-xs bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:opacity-60 text-zinc-900 dark:text-zinc-100"
          />
        </div>

        {/* Optional compact deadline picker & Action button */}
        <div className="flex gap-2.5 items-center">
          <div className="relative flex-1">
            <Calendar className="absolute left-2.5 top-2.5 w-3 h-3 text-zinc-400 pointer-events-none" />
            <input
              id="goal-deadline"
              type="date"
              value={deadline}
              onChange={(e) => setDeadline(e.target.value)}
              disabled={isLoading}
              className="w-full pl-7 pr-2 py-1.5 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg focus:outline-none focus:ring-1 focus:ring-indigo-500 disabled:opacity-60 text-zinc-900 dark:text-zinc-100 text-[11px]"
            />
          </div>

          <button
            id="btn-trigger-ai-breakdown"
            type="submit"
            disabled={isLoading || !title.trim()}
            className="px-4 py-1.5 bg-zinc-900 hover:bg-zinc-800 dark:bg-zinc-100 dark:hover:bg-zinc-200 text-white dark:text-zinc-900 rounded-lg font-bold text-[11px] shadow transition-all duration-200 disabled:opacity-40 active:scale-[0.98] shrink-0"
          >
            {isLoading ? 'Formulating...' : 'Deconstruct'}
          </button>
        </div>

        {error && (
          <p className="text-[10px] text-red-500 mt-1">{error}</p>
        )}
      </form>
    </div>
  );
}
